version: 2.1
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo Installing dependencies
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
    scan:
      docker:
        - image: cimg/node:16.10
      environment:
        IMAGE_NAME: shayne96/6m-software-m4-node-app-for-devops
      steps:
        - checkout
        - setup_remote_docker
        - docker/check
        - run: docker build -t $IMAGE_NAME .
        - snyk/scan:
            docker-image-name: $IMAGE_NAME
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: shayne96/6m-software-m4-node-app-for-devops
      - docker/push:
          image: shayne96/6m-software-m4-node-app-for-devops
  publish:
    docker:
      - image: docker:20.10.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t shayne96/6m-software-m4-node-app-for-devops:tagname .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push shayne96/6m-software-m4-node-app-for-devops:tagname
  deploy:
    docker:
        - image: cimg/node:16.10
    steps:
        - setup_remote_docker      
        - heroku/install
        - checkout
        - run:
            name: Heroku Container Push
            command: | 
                heroku container:login
                heroku container:push web -a shayne-devops
                heroku container:release web -a shayne-devops
workflows:
  simple_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:main
      - test:
          requires:
            - build
          filters:
            branches:
              only:main
      - scan:
          requires:
            - test
          filters:
            branches:
              only:main