version: 2.1
orbs:
  node: circleci/node@5.0.1
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo Installing dependencies
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: shayne96/6m-software-m4-node-app-for-devops
      - docker/push:
          image: shayne96/6m-software-m4-node-app-for-devops
  publish:
    docker:
      - image: docker:20.10.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker build -t shayne96/6m-software-m4-node-app-for-devops:tagname .
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push shayne96/6m-software-m4-node-app-for-devops:tagname
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test